inherits = "nvim-light"

[palette]
NvimDarkYellow = "#fce094"
NvimDarkRed = "#ffc0b9"
NvimDarkMagenta = "#ffcaff"
NvimDarkGrey4 = "#9b9ea4"
NvimDarkGrey3 = "#c4c6cd"
NvimDarkGrey2 = "#e0e2ea"
NvimDarkGrey1 = "#eef1f8"
NvimDarkGreen = "#b3f6c0"
NvimDarkGray4 = "#9b9ea4"
NvimDarkGray3 = "#c4c6cd"
NvimDarkGray2 = "#e0e2ea"
NvimDarkGray1 = "#eef1f8"
NvimDarkCyan = "#8cf8f7"
NvimDarkBlue = "#a6dbff"
NvimLightYellow = "#6b5300"
NvimLightRed = "#590008"
NvimLightMagenta = "#470045"
NvimLightGrey4 = "#4f5258"
NvimLightGrey3 = "#2c2e33"
NvimLightGrey2 = "#14161b"
NvimLightGrey1 = "#07080d"
NvimLightGreen = "#005523"
NvimLightGray4 = "#4f5258"
NvimLightGray3 = "#2c2e33"
NvimLightGray2 = "#14161b"
NvimLightGray1 = "#07080d"
NvimLightCyan = "#007373"
NvimLightBlue = "#004c73"
